import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Playfair_Display, Montserrat } from 'next/font/google';
import '@/styles/globals.css';
import '@/styles/main.scss';
import { LangType } from '@/types';

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['700'],
  display: 'swap',
  variable: '--font-playfair-display',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600'],
  display: 'swap',
  variable: '--font-montserrat',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'id' }];
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: LangType };
}) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${playfairDisplay.variable}`}
    >
      <body className="font-sans antialiased text-body bg-bg">
        <div className="">
          <div className="bg-bg flex flex-col min-h-screen">
            <Header params={params} />
            <div className="flex-1">{children}</div>
            <Footer params={params} />
          </div>
        </div>
      </body>
    </html>
  );
}
