export type CvListType = typeof cvList;

export const cvList = [
  {
    title: "Education",
    items: [
      {
        title: "Doctor of Sacred Theology",
        subtitle: null,
        institution: "Pontifical University of the Holy Cross",
        date: ["2022 – 2024"],
        badges: ["Summa cum laude"],
      },
      {
        title: "Licentiate in Dogmatic Theology",
        subtitle: null,
        institution: "Pontifical University of the Holy Cross",
        date: ["2020 – 2022"],
        badges: ["Summa cum laude"],
      },
      {
        title: "Baccalaureate in Philosophy",
        subtitle: null,
        institution: "University of Navarra",
        date: ["2013 – 2015", "2018 – 2019"],
        badges: ["Summa cum laude"],
      },
      {
        title: "Baccalaureate in Theology",
        subtitle: null,
        institution: "University of Navarra",
        date: ["2015 – 2018"],
        badges: ["Summa cum laude"],
      },
      {
        title: `Piano Performance`,
        subtitle: null,
        institution: "Missouri Western State University",
        date: ["2010 – 2012"],
      },
    ],
  },
  {
    title: "Languages",
    items: [
      { title: "English", badges: ["Reading", "Speaking", "Writing"] },
      { title: "Spanish", badges: ["Reading", "Speaking", "Writing"] },
      { title: "Italian", badges: ["Reading", "Speaking", "Writing"] },
      { title: "Bahasa Indonesia", badges: ["Reading", "Speaking", "Writing"] },
      { title: "Latin", badges: ["Reading"] },
      { title: "French", badges: ["Reading"] },
    ],
  },
  {
    title: "Academic Experience",
    items: [
      {
        title: "Teaching Assistant",
        institution: "Pontifical University of the Holy Cross",
        date: ["Since Oct 2022"],
        location: "Rome, Italy",
        active: true,
      },
      {
        title: "Lecturer",
        institution: "University of Ciputra",
        date: ["Sep 2019 – May 2020"],
        location: "Surabaya, Indonesia",
        description: `I taught Philosophy of Religion, both in English and in Bahasa Indonesia, to junior students of different majors.`,
      },
      {
        title: "Lecturer",
        institution: "Katolisitas Study Group",
        date: ["Jul 2019 – May 2020"],
        location: "Jakarta, Indonesia",
        description: `I taught St. Thomas Aquinas’ Summa Theologiae to a group of catechists.`,
      },
      {
        title: "Lecturer",
        institution: "St. John Vianney Spiritual Year Seminary",
        date: ["Aug 2018 – Jun 2020"],
        location: "Surabaya, Indonesia",
        description: `I taught Introduction to Sacred Scripture course to seminarians.`,
      },
      {
        title: "Translator",
        institution: "University of Navarra",
        date: ["Sep 2014 – Jul 2020"],
        location: "Surabaya, Indonesia",
        description: `I collaborated with some professors and the editors of Scripta Theologica journal of theology on the translation of abstracts and articles from Spanish to English, as well as on the revision thereof.`,
      },
      {
        title: "Lab Coordinator",
        institution: "Missouri Western State University",
        date: ["Mar — Dec 2011"],
        location: "Missouri, USA",
        description: `In this University's Department of English and Modern Languages, I administered placement tests for incoming freshmen, organized teaching materials for Reading 095 faculty members, and assisted the director in putting together the end-of-semester report. Finally, I composed a Reading 095 Lab Coordinator Manual for future use.`,
      },
      {
        title: "Piano Instructor",
        institution: "Concerto Music School",
        date: ["2008 – 2010"],
        location: "Jakarta, Indonesia",
        description: `I focused on providing elementary music instructions to children as well as giving private piano lessons.`,
      },
    ],
  },
  {
    title: "Speaking Topics",
    items: [
      {
        title: "The Purpose of Life",
        date: ["22 Jan 2022"],
        location: "Singapore",
      },
      { title: "Forgiveness", date: ["11 Nov 2021"], location: "Singapore" },
      {
        title: "Mary in Today’s World",
        date: ["25 Oct 2021"],
        location: "Surabaya",
      },
      {
        title: "Abortion according to Catholic Morality",
        date: ["23 Oct 2021"],
        location: "Surabaya",
      },
      {
        title: "Rosary: Why and How to Pray It",
        date: ["16 Oct 2021"],
        location: "Jakarta",
      },
      {
        title: "Chastity and Contraception",
        date: ["11 Oct 2021"],
        location: "Jakarta",
      },
      {
        title: "Seven Anti-Catholic Myths",
        date: ["24 Sep 2021"],
        location: "Jakarta",
      },
      {
        title: "Seven Habits of Prayer",
        date: ["23 Sep 2021"],
        location: "Singapore",
      },
      {
        title: "Extra Ecclesiam Nulla Salus",
        date: ["15 Sep 2021"],
        location: "Surabaya",
      },
      {
        title: "Growing in Faith",
        location: "Singapore",
        date: ["14 Sep 2021"],
      },
      { title: "Antichrist", location: "Jakarta", date: ["10 Sep 2021"] },
      { title: "Prosperity Gospel", location: "Jakarta", date: ["5 Sep 2021"] },
      {
        title: "The Ninth and Tenth Commandments",
        location: "Jakarta",
        date: ["7 Aug 2021"],
      },
      {
        title: "Christian Poverty and Detachment",
        location: "Jakarta",
        date: ["22 Jul 2021"],
      },
      {
        title: "Second Vatican Council",
        location: "Surabaya",
        date: ["21 Jul 2021"],
      },
      {
        title: "The Fifth Commandment",
        location: "Jakarta",
        date: ["10 Jul 2021"],
      },
      { title: "The Trinity", location: "Singapore", date: ["18 Jul 2020"] },
      { title: "The Holy Spirit", location: "Surabaya", date: ["27 MAY 2020"] },
      {
        title: "Catholicism vs. Protestantism",
        location: "22 MAY 2020, JAKARTA",
      },
      { title: "The Problem of Evil", location: "11 MAY 2020, CALIFORNIA" },
      {
        title: "The Divine Mercy",
        location: "Surabaya",
        date: ["15 APRIL 2020"],
      },
      {
        title: "The Way of the Cross",
        location: "Surabaya",
        date: ["7 MARCH 2020"],
      },
      { title: "New Age", location: "Surabaya", date: ["4 MARCH 2020"] },
      { title: "Priestly Vocation", location: "13 FEBRUARY 2020, JAKARTA" },
      {
        title: "God’s Existence",
        location: "Surabaya",
        date: ["27 JANUARY 2020"],
      },
      {
        title: "The Eucharist",
        location: "Surabaya",
        date: ["7 DECEMBER 2019"],
      },
      {
        title: "On the “Our Father”",
        location: "Surabaya",
        date: ["21 Nov 2019"],
      },
      { title: "Purgatory", location: "Surabaya", date: ["20 Nov 2019"] },
      {
        title: "Liturgical Items and Vestments",
        location: "Surabaya",
        date: ["27 OCTOBER 2019"],
      },
      {
        title: "Aquinas: Life and Teaching",
        location: "Surabaya",
        date: ["26 OCTOBER 2019"],
      },
      {
        title: "History and Content of the CCC",
        location: "Surabaya",
        date: ["19 SEPTEMBER 2019"],
      },
      {
        title: "Christian Family",
        location: "Surabaya",
        date: ["31 Aug 2019"],
      },
      {
        title: "Reasons to be a Catholic",
        location: "Surabaya",
        date: ["3 JULY 2019"],
      },
      { title: "Sins", location: "Surabaya", date: ["22 JULY 2019"] },
      { title: "Christology", location: "Jakarta", date: ["29 Jun 2019"] },
      { title: "The Last Things", location: "Surabaya", date: ["12 MAY 2019"] },
      {
        title: "The Sacrament of Baptism",
        location: "Surabaya",
        date: ["11 APRIL 2019"],
      },
      {
        title: "Human Passions",
        location: "Surabaya",
        date: ["16 MARCH 2019"],
      },
      { title: "Superstition", location: "Surabaya", date: ["14 MARCH 2019"] },
      {
        title: "Biblical Covenants",
        location: "Surabaya",
        date: ["13 FEBRUARY 2019"],
      },
      {
        title: "Christian Prayer",
        location: "Surabaya",
        date: ["13 FEBRUARY 2019"],
      },
      {
        title: "“Adoro te devote”",
        location: "Surabaya",
        date: ["1 FEBRUARY 2019"],
      },
      {
        title: "The Sacrament of Confession",
        location: "Surabaya",
        date: ["7 DECEMBER 2018"],
      },
      {
        title: "History of the Church",
        location: "Surabaya",
        date: ["21 Nov 2018"],
      },
      {
        title: "Holy Communion",
        location: "Surabaya",
        date: ["13 Nov 2018"],
      },
      {
        title: "Our Lady of Torreciudad",
        location: "Surabaya",
        date: ["Oct 14, 2018"],
      },
      {
        title: "Marian Devotion",
        location: "Surabaya",
        date: ["Oct 11, 2018"],
      },
      {
        title: "Queen of Rosary",
        location: "Surabaya",
        date: ["Oct 5, 2018"],
      },
      {
        title: "Pipe Organs 101",
        location: "Surabaya",
        date: ["Sep 30, 2018"],
      },
    ],
  },
  {
    title: "Areas of Interest",
    items: [
      { title: "St. Thomas Aquinas" },
      { title: "Theology of Creation" },
      { title: "Medieval Philosophy and Theology" },
      { title: "Apologetics and Catechesis" },
      { title: "Pipe Organ" },
      { title: "Renaissance Art" },
    ],
  },
  {
    title: "Pastoral Experience",
    items: [
      {
        title: "Associate Priest",
        institution: "Parish of Santo Yakobus",
        date: ["Jun 2019 – Jul 2020"],
        location: "Surabaya",
        description: `I administered the sacraments, preached, and imparted catechesis to parishioners of different age groups. I was in charge of St. John Paul II’s Chapel attached to the parish. I also regularly gave talks to a group of young married couples.`,
      },
      {
        title: "Chaplain",
        subtitle: "Pilgrimage to Holy Land",
        date: ["Oct 2029"],
        location: "Israel",
        description: `I accompanied a group of thirteen pilgrims from Indonesia. I celebrated Mass daily, gave meditations, and provided doctrinal as well as historical explanations of the places we visited.`,
      },
      {
        title: "Spiritual Director",
        institution: "St. Vincent de Paul’s Catholic Hospital’s Nursing School",
        date: ["Feb – May 2019"],
        location: "Surabaya",
        description: `I gave a series of recollections and catechesis classes to Catholic students at St. Vincent de Paul’s Catholic Hospital’s Nursing School.`,
      },
      {
        title: "Transitional Deacon",
        institution: "Cathedral of the Sacred Heart",
        location: "Surabaya",
        date: ["Sep 2018 – May 2019"],
      },
    ],
  },
  {
    title: "Volunteer Experience",
    items: [
      {
        title: "Organist",
        institution: "Clínica Universidad de Navarra",
        date: ["Sep 2016 – Jun 2018"],
        location: "Pamplona, Spain",
        description: `I helped the University of Navarra's chaplain for English-speaking students, Fr. José Alviar, organize the choir for the Mass celebrated in English on Sundays during the entire school year.`,
      },
      {
        title: "Pilgrim Guide",
        institution: "Shrine of Torreciudad",
        date: ["Jul 2017"],
        location: "Huesca, Spain",
        description: `I toured the pilgrims around the Shrine and gave them succinct historical explanations of this pilgrimage site. I also assisted the staff at the Information Service Center in attending to the needs of the visitors.`,
      },
      {
        title: "Caretaker",
        institution: "Centro de Apoio a Deficientes João Paulo II",
        date: ["Jun 2017"],
        location: "Fátima, Portugal",
        description: `I took care of those living with mental illnesses by changing their soiled bedding, feeding them, taking them out for a walk, and entertaining them.`,
      },
      {
        title: "Organist",
        institution: "Catholic Newman Center",
        date: ["2010 – 2011"],
        location: "Missouri, USA",
        description: `I selected the hymns and accompanied the assembly in Sunday Masses celebrated at Missouri Western State University’s Catholic Newman Center.`,
      },
      {
        title: "Vice President",
        institution: "Catholic Newman Center",
        date: ["2010 – 2011"],
        location: "Missouri, USA",
        description: `I assisted the Director in preparing and carrying out Missouri Western State University’s Catholic Newman Center's programs, such as summer fundraising and dinner after Sunday Mass.`,
      },
    ],
  },
];
